# Generated by Django 6.0.8 on 2026-08-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_company_partner_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Sunlight Group', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='sunlight-group', unique=True),
        ),
    ]
