# Generated by Django 6.0.8 on 2026-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_partnershiprequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='GoldenSunlight', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='goldensunlight', unique=True),
        ),
    ]
