# Generated by Django 6.0.8 on 2026-09-08 16:49

from django.db import migrations, models

# Yetkazib berish bosqichlari olib tashlandi (endi faqat pickup) — eski qiymatlar
# yangi 3-bosqichli oqimga (pending -> preparing -> ready) moslashtiriladi.
OLD_TO_NEW = {
    'confirmed': 'preparing',
    'processing': 'preparing',
    'packaging': 'preparing',
    'delivering': 'ready',
    'delivered': 'ready',
}


def remap_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for old_status, new_status in OLD_TO_NEW.items():
        Order.objects.filter(status=old_status).update(status=new_status)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_method'),
    ]

    operations = [
        migrations.RunPython(remap_statuses, noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Processing'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
