# Generated by Django 6.0.8 on 2026-09-08 18:15

from django.db import migrations

# 0010 default'ni 15 -> 0 ga o'zgartirdi, lekin bu faqat YANGI qatorlarga taalluqli —
# mavjud buyurtmalarda delivery_fee=15 saqlanib qolgan va total_amount shuni ichiga
# olgan edi (frontend'da "Delivery" qatori olib tashlangach, Total mahsulotlar
# yig'indisidan AED 15 ko'proq ko'rinardi). Bu migratsiya barcha mavjud buyurtmalarni
# delivery_fee=0 ga o'tkazib, total_amount'ni qayta hisoblaydi.


def backfill(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.exclude(delivery_fee=0):
        order.delivery_fee = 0
        order.total_amount = max(
            order.subtotal - order.discount_amount + order.tax_amount, 0
        )
        order.save(update_fields=['delivery_fee', 'total_amount'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_delivery_fee'),
    ]

    operations = [
        migrations.RunPython(backfill, noop),
    ]
