# Generated by Django 6.0.8 on 2026-09-17 14:15

from django.db import migrations, models


def backfill_picked_up_at(apps, schema_editor):
    """Bu maydon qo'shilishidan OLDIN allaqachon `picked_up` bo'lgan buyurtmalar uchun
    haqiqiy o'tish sanasi noma'lum (alohida saqlanmagan). `updated_at`ni yaqinlashtirish
    sifatida ishlatamiz — `picked_up`/cancelled/refunded/ready singari TERMINAL_STATUSES'ga
    o'tgach buyurtma boshqa tahrirlanmaydi (orders/views.py), shuning uchun bu buyurtmalar
    uchun `updated_at` odatda aynan shu status o'zgarishi paytidagi vaqt bo'ladi. Bo'lmasa
    ham bu faqat migratsiyadan OLDINGI tarixiy ma'lumotlar uchun taxminiy qiymat — yangi
    buyurtmalar `AdminOrderStatusView.post`da aniq belgilanadi."""
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='picked_up', picked_up_at__isnull=True).update(picked_up_at=models.F('updated_at'))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_picked_up_at, noop_reverse),
    ]
