"""Full product catalog data, generated from real GoldenSunlight product
photography (see Mockups/ and backend/seed_assets/products/). Consumed by
seed.py — do not hand-edit individual entries here; regenerate via the
cataloging pipeline if the source photos change."""

PRODUCTS_DATA = [
    {
        'name': 'Natural Fresh Infante Baby Wet Wipes',
        'slug': 'natural-fresh-infante-baby-wet-wipes',
        'description': 'Gentle, alcohol-free baby wet wipes with a neutral pH, packed in a cloud-print pouch with a fun bear design for everyday infant care.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-001',
        'stock': 40,
        'rating': 3.9,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '2.png',
    },
    {
        'name': 'Rio Premium Baby Wet Wipes',
        'slug': 'rio-premium-baby-wet-wipes',
        'description': 'Premium alcohol- and paraben-free baby wipes enriched with Vitamin E and Provitamin B5 for soft, gentle cleansing.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-002',
        'stock': 50,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '3.png',
    },
    {
        'name': 'Sunlight Kids Bunny Wet Wipes',
        'slug': 'sunlight-kids-bunny-wet-wipes',
        'description': "Alcohol-free, pH-balanced kids' wet wipes in a cheerful heart-print pack featuring a bunny character.",
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'BKW-003',
        'stock': 60,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '4.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes (Blue)',
        'slug': 'sunlight-antibacterial-wet-wipes-blue',
        'description': 'Antibacterial wet wipes in blue packaging formulated to stop bacteria for everyday hygiene on the go.',
        'price': 5.9,
        'old_price': 7.11,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': '-17%',
        'sku': 'UNW-001',
        'stock': 70,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '5.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes (Violet)',
        'slug': 'sunlight-antibacterial-wet-wipes-violet',
        'description': 'Antibacterial wet wipes in violet packaging formulated to stop bacteria for everyday hygiene on the go.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-002',
        'stock': 80,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '5kara.png',
    },
    {
        'name': 'Sunlight Universal Wet Towels',
        'slug': 'sunlight-universal-wet-towels',
        'description': 'Universal wet towels designed for daily personal hygiene, packaged 20 to a pack.',
        'price': 3.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-003',
        'stock': 100,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '7.png',
    },
    {
        'name': 'Sunlight Butterfly Universal Wet Wipes with Cream (120 pcs)',
        'slug': 'sunlight-butterfly-universal-wet-wipes-with',
        'description': 'Fragrance-free, alcohol-free universal wet wipes enriched with cream, packaged in a large 120-count Extra Pack with a butterfly design.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-004',
        'stock': 110,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '10.png',
    },
    {
        'name': 'Sunlight Baby Wet Wipes Sensitive & Soft (120 pcs)',
        'slug': 'sunlight-baby-wet-wipes-sensitive-soft-120',
        'description': 'Alcohol-free, pH-balanced baby wipes formulated to be sensitive and soft on delicate skin, in a large 120-count pack.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-004',
        'stock': 120,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '11.png',
    },
    {
        'name': 'Sunlight Kids Wet Wipes (120 pcs)',
        'slug': 'sunlight-kids-wet-wipes-120-pcs',
        'description': "Alcohol-free, pH-balanced kids' wet wipes in a playful koala-and-owl print pack, 120 count.",
        'price': 4.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'BKW-005',
        'stock': 130,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '12.png',
    },
    {
        'name': 'Sunlight Kids Wet Wipes (72 pcs)',
        'slug': 'sunlight-kids-wet-wipes-72-pcs',
        'description': "Alcohol-free, pH-balanced kids' wet wipes in a playful koala-and-owl print pack, 72 count.",
        'price': 3.5,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-006',
        'stock': 140,
        'rating': 4.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '13.png',
    },
    {
        'name': 'Sunlight Baby Wet Wipes – Bear & Zebra (120 pcs)',
        'slug': 'sunlight-baby-wet-wipes-bear-zebra-120-pcs',
        'description': 'Alcohol- and paraben-free baby wet wipes at pH 5.5, packaged with a playful bear-and-zebra print, 120 count.',
        'price': 4.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-007',
        'stock': 150,
        'rating': 3.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '14.png',
        'gallery_files': ['15.png'],
    },
    {
        'name': 'Sunlight Baby Wet Wipes – Bear & Zebra (72 pcs)',
        'slug': 'sunlight-baby-wet-wipes-bear-zebra-72-pcs',
        'description': 'Alcohol- and paraben-free baby wet wipes at pH 5.5, packaged with a playful bear-and-zebra print, 72 count.',
        'price': 3.5,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-008',
        'stock': 40,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '15.png',
    },
    {
        'name': 'Sunlight Baby Wet Wipes – Owl & Fox (120 pcs)',
        'slug': 'sunlight-baby-wet-wipes-owl-fox-120-pcs',
        'description': 'Alcohol- and paraben-free baby wet wipes at pH 5.5, featuring a charming owl-and-fox village print, 120 count.',
        'price': 4.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-009',
        'stock': 50,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '16.png',
    },
    {
        'name': 'Sunlight Baby Wet Wipes – Owl & Fox (72 pcs)',
        'slug': 'sunlight-baby-wet-wipes-owl-fox-72-pcs',
        'description': 'Alcohol- and paraben-free baby wet wipes at pH 5.5, featuring a charming owl-and-fox village print, 72 count.',
        'price': 3.5,
        'old_price': 4.22,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'badge': '-17%',
        'sku': 'BKW-010',
        'stock': 60,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '17.png',
    },
    {
        'name': 'Sunlight Baby Wet Wipes – Giraffe (120 pcs)',
        'slug': 'sunlight-baby-wet-wipes-giraffe-120-pcs',
        'description': 'Alcohol- and paraben-free baby wet wipes at pH 5.5, decorated with a cheerful giraffe print, 120 count.',
        'price': 4.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-011',
        'stock': 70,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '18.png',
    },
    {
        'name': 'Sunlight Baby Wet Wipes – Giraffe (72 pcs)',
        'slug': 'sunlight-baby-wet-wipes-giraffe-72-pcs',
        'description': 'Alcohol- and paraben-free baby wet wipes at pH 5.5, decorated with a cheerful giraffe print, 72 count.',
        'price': 3.5,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'BKW-012',
        'stock': 80,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '19.png',
    },
    {
        'name': 'Sunlight Chamomile Baby Wet Wipes (72 pcs)',
        'slug': 'sunlight-chamomile-baby-wet-wipes-72-pcs',
        'description': 'Alcohol- and paraben-free chamomile-infused baby wet wipes at pH 5.5, in a daisy-print pack, 72 count.',
        'price': 3.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-013',
        'stock': 90,
        'rating': 4.5,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '20.png',
    },
    {
        'name': 'Sunlight Chamomile Baby Wet Towels (72 pcs)',
        'slug': 'sunlight-chamomile-baby-wet-towels-72-pcs',
        'description': 'Alcohol- and paraben-free chamomile-infused baby wet towels at pH 5.5, in a daisy-print pack, 72 count.',
        'price': 3.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-014',
        'stock': 100,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '21.png',
    },
    {
        'name': 'Sunlight Rose Wet Wipes (72 pcs)',
        'slug': 'sunlight-rose-wet-wipes-72-pcs',
        'description': 'Alcohol- and paraben-free rose-scented wet wipes at pH 5.5, packaged 72 to a pack.',
        'price': 3.8,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-005',
        'stock': 110,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '22.png',
    },
    {
        'name': 'Sunlight Universal Wet Towels XXL (70 pcs)',
        'slug': 'sunlight-universal-wet-towels-xxl-70-pcs',
        'description': 'Extra-large universal wet towels for daily personal hygiene, sized 250x250mm and packed 70 to a pack.',
        'price': 3.8,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-006',
        'stock': 120,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '23.png',
    },
    {
        'name': 'Sunlight For Home Wet Wipes XL (70 pcs)',
        'slug': 'sunlight-for-home-wet-wipes-xl-70-pcs',
        'description': 'XL household cleaning wipes with a unique foaming formula that leave floors, mirrors, and other surfaces streak-free, 70 count.',
        'price': 13.9,
        'category_slug': 'household-cleaning',
        'brand_slug': 'sunlight',
        'sku': 'HCL-002',
        'stock': 130,
        'rating': 4.9,
        'ingredients': 'Non-woven viscose-blend fabric, mild surfactant',
        'image_file': '24.png',
    },
    {
        'name': 'Sunlight For Kitchen Abrasive Wet Wipes XL (40 pcs)',
        'slug': 'sunlight-for-kitchen-abrasive-wet-wipes-xl',
        'description': 'XL abrasive wet wipes designed to cut through kitchen grease and grime, with an antibacterially protected scrubbing surface, 40 count.',
        'price': 4.2,
        'category_slug': 'household-cleaning',
        'brand_slug': 'sunlight',
        'sku': 'HCL-003',
        'stock': 140,
        'rating': 3.9,
        'ingredients': 'Non-woven viscose-blend fabric, mild surfactant',
        'image_file': '25.png',
    },
    {
        'name': 'Sunlight Universal Cotton Wet Towels XL (20 pcs)',
        'slug': 'sunlight-universal-cotton-wet-towels-xl-20',
        'description': 'Cotton-soft XL wet towels for everyday personal hygiene, packaged 20 to a pack.',
        'price': 3.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'UNW-007',
        'stock': 150,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '26.png',
    },
    {
        'name': 'Sunlight Premium Wet Wipes (20 pcs)',
        'slug': 'sunlight-premium-wet-wipes-20-pcs',
        'description': 'Premium wet wipes in a sleek black-and-orange geometric pack, 20 count.',
        'price': 3.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-008',
        'stock': 40,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '27.png',
    },
    {
        'name': 'Sunlight Deluxe Wet Wipes (20 pcs)',
        'slug': 'sunlight-deluxe-wet-wipes-20-pcs',
        'description': 'Deluxe wet wipes in an upscale black-and-gold marble-print pack, 20 count.',
        'price': 3.0,
        'old_price': 3.61,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': '-17%',
        'sku': 'UNW-009',
        'stock': 50,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '28.png',
    },
    {
        'name': 'Sunlight Make-Up Remover Wipes (20 pcs)',
        'slug': 'sunlight-make-up-remover-wipes-20-pcs',
        'description': 'Wet wipes formulated for makeup removal, packaged in a pink-and-gold floral pack of 20.',
        'price': 3.0,
        'category_slug': 'specialty-wipes',
        'brand_slug': 'sunlight',
        'sku': 'SPW-001',
        'stock': 60,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, mild surfactant, plant extract, fragrance',
        'image_file': '29.png',
    },
    {
        'name': 'Sunlight Intimate Hygiene Wipes (20 pcs)',
        'slug': 'sunlight-intimate-hygiene-wipes-20-pcs',
        'description': 'Wet wipes formulated for intimate hygiene, packaged in a soft pink-and-blue floral pack of 20.',
        'price': 3.0,
        'category_slug': 'specialty-wipes',
        'brand_slug': 'sunlight',
        'sku': 'SPW-002',
        'stock': 70,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, mild surfactant, plant extract, fragrance',
        'image_file': '30.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes XL (Blue)',
        'slug': 'sunlight-antibacterial-wet-wipes-xl-blue',
        'description': 'XL-size antibacterial wet wipes in blue packaging formulated to stop bacteria for everyday hygiene.',
        'price': 1.5,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-010',
        'stock': 80,
        'rating': 4.5,
        'is_featured': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '31.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes XL (Violet)',
        'slug': 'sunlight-antibacterial-wet-wipes-xl-violet',
        'description': 'XL-size antibacterial wet wipes in violet packaging formulated to stop bacteria for everyday hygiene.',
        'price': 1.5,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-011',
        'stock': 90,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '32.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes Violet (120 pcs)',
        'slug': 'sunlight-antibacterial-wet-wipes-violet-120',
        'description': 'Antibacterial wet wipes offering maximum protection from bacteria, in a bold violet lightning-print pack of 120.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'UNW-012',
        'stock': 100,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '33.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes Silver (120 pcs)',
        'slug': 'sunlight-antibacterial-wet-wipes-silver-120',
        'description': 'Fragrance-free antibacterial wet wipes offering maximum protection from bacteria, in a silver-toned pack of 120.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-013',
        'stock': 110,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '34.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes Silver (72 pcs)',
        'slug': 'sunlight-antibacterial-wet-wipes-silver-72',
        'description': 'Fragrance-free antibacterial wet wipes offering maximum protection from bacteria, in a silver-toned pack of 72.',
        'price': 3.8,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-014',
        'stock': 120,
        'rating': 4.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '35.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes Blue (120 pcs)',
        'slug': 'sunlight-antibacterial-wet-wipes-blue-120-pcs',
        'description': 'Antibacterial wet wipes offering maximum protection from bacteria, in a deep blue lightning-print pack of 120.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-015',
        'stock': 130,
        'rating': 3.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '36.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes Blue (72 pcs)',
        'slug': 'sunlight-antibacterial-wet-wipes-blue-72-pcs',
        'description': 'Antibacterial wet wipes offering maximum protection from bacteria, in a deep blue lightning-print pack of 72.',
        'price': 3.8,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-016',
        'stock': 140,
        'rating': 4.0,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '37.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes (15 pcs, Blue/Violet)',
        'slug': 'sunlight-antibacterial-wet-wipes-15-pcs-blue',
        'description': 'Compact 15-count antibacterial wet wipes offering maximum protection from bacteria, in a portrait-format pack.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-017',
        'stock': 150,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '38.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes (15 pcs, Pink)',
        'slug': 'sunlight-antibacterial-wet-wipes-15-pcs-pink',
        'description': 'Compact 15-count antibacterial wet wipes offering maximum protection from bacteria, in a portrait-format pack with a pink color scheme.',
        'price': 1.0,
        'old_price': 1.22,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': '-18%',
        'sku': 'UNW-018',
        'stock': 40,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '39.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipe Single Sachet',
        'slug': 'sunlight-antibacterial-wet-wipe-single-sachet',
        'description': 'A single-use antibacterial wet wipe sachet offering maximum protection from bacteria, ideal for travel or on-the-go use.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'UNW-019',
        'stock': 50,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '40.png',
        'gallery_files': ['41.png'],
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipe Single Sachet',
        'slug': 'sunlight-antibacterial-wet-wipe-single-sachet-2',
        'description': 'A single-use antibacterial wet wipe sachet offering maximum protection from bacteria, ideal for travel or on-the-go use.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-020',
        'stock': 60,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '41.png',
    },
    {
        'name': 'Sunlight Parfum Woman Wet Wipes (15 pcs)',
        'slug': 'sunlight-parfum-woman-wet-wipes-15-pcs',
        'description': 'Alcohol- and paraben-free perfumed wet wipes for women, packaged in a vibrant floral 15-count pack.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-021',
        'stock': 70,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '42.png',
    },
    {
        'name': 'Sunlight Parfum Woman Wet Wipes (Blue)',
        'slug': 'sunlight-parfum-woman-wet-wipes-blue',
        'description': 'Alcohol-free and paraben-free scented wet wipes for women in an elegant blue floral pack of 15.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-022',
        'stock': 80,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '43.png',
    },
    {
        'name': 'Sunlight Parfum Woman Wet Wipes (Red & Gold)',
        'slug': 'sunlight-parfum-woman-wet-wipes-red-gold',
        'description': 'Alcohol-free and paraben-free scented wet wipes for women in a luxe red and gold pack of 15.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-023',
        'stock': 90,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '44.png',
    },
    {
        'name': 'Sunlight Parfum Woman Wet Wipes (Pink)',
        'slug': 'sunlight-parfum-woman-wet-wipes-pink',
        'description': 'Alcohol-free and paraben-free scented wet wipes for women in a soft pink floral pack of 15.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-024',
        'stock': 100,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '45.png',
    },
    {
        'name': 'Sunlight Parfum Man Wet Wipes (Blue)',
        'slug': 'sunlight-parfum-man-wet-wipes-blue',
        'description': 'Alcohol-free and paraben-free scented wet wipes for men in a blue textured pack of 15.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-025',
        'stock': 110,
        'rating': 4.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '46.png',
    },
    {
        'name': 'Sunlight Parfum Man Wet Wipes (Silver)',
        'slug': 'sunlight-parfum-man-wet-wipes-silver',
        'description': 'Alcohol-free and paraben-free scented wet wipes for men in a silver pack featuring a cologne-bottle graphic, 15 count.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'UNW-026',
        'stock': 120,
        'rating': 3.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '47.png',
    },
    {
        'name': 'Sunlight Parfum Man Wet Wipes (Black & Yellow)',
        'slug': 'sunlight-parfum-man-wet-wipes-black-yellow',
        'description': 'Alcohol-free and paraben-free scented wet wipes for men in a bold black and yellow pack of 15.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-027',
        'stock': 130,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '49.png',
    },
    {
        'name': 'Sunlight Flower Fantasy Wet Wipes (Pink Plumeria)',
        'slug': 'sunlight-flower-fantasy-wet-wipes-pink',
        'description': 'Floral-scented wet wipes in a vivid pink pack featuring tropical plumeria flowers, 15 count.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-028',
        'stock': 140,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '50.png',
    },
    {
        'name': 'Sunlight Flower Fantasy Wet Wipes (Blue Dandelion)',
        'slug': 'sunlight-flower-fantasy-wet-wipes-blue',
        'description': 'Floral-scented wet wipes in a deep blue pack with a glowing dandelion design, 15 count.',
        'price': 1.0,
        'old_price': 1.22,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': '-18%',
        'sku': 'UNW-029',
        'stock': 150,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '51.png',
    },
    {
        'name': 'Sunlight Flower Fantasy Wet Wipes (Cherry Blossom)',
        'slug': 'sunlight-flower-fantasy-wet-wipes-cherry',
        'description': 'Floral-scented wet wipes in a soft pastel pack decorated with cherry blossom branches, 15 count.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-030',
        'stock': 40,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '52.png',
    },
    {
        'name': 'Sunlight Flower Fantasy Wet Wipes (White Blossom)',
        'slug': 'sunlight-flower-fantasy-wet-wipes-white',
        'description': 'Floral-scented wet wipes in a dark blue-purple pack with delicate white flowers, 15 count.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-031',
        'stock': 50,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '53.png',
    },
    {
        'name': 'Sunlight Orange Wet Wipes',
        'slug': 'sunlight-orange-wet-wipes',
        'description': 'Refreshing orange-scented wet wipes with a vibrant citrus design, 15 count.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-032',
        'stock': 60,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '54.png',
    },
    {
        'name': 'Sunlight Lime Wet Wipes',
        'slug': 'sunlight-lime-wet-wipes',
        'description': 'Refreshing lime-scented wet wipes with a vibrant green citrus design, 15 count.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'UNW-033',
        'stock': 70,
        'rating': 4.6,
        'is_popular': True,
        'is_featured': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '55.png',
    },
    {
        'name': 'Sunlight Lemon Wet Wipes',
        'slug': 'sunlight-lemon-wet-wipes',
        'description': 'Refreshing lemon-scented wet wipes with a vibrant yellow citrus design, 15 count.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-034',
        'stock': 80,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '56.png',
    },
    {
        'name': 'Sunlight Grapefruit Wet Wipes',
        'slug': 'sunlight-grapefruit-wet-wipes',
        'description': 'Refreshing grapefruit-scented wet wipes with a vibrant citrus splash design, 15 count.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-035',
        'stock': 90,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '57.png',
    },
    {
        'name': 'Sunlight Kids Wet Wipes (Bunny)',
        'slug': 'sunlight-kids-wet-wipes-bunny',
        'description': 'Gentle alcohol-free, pH-balanced wet wipes for kids featuring a cute bunny character, 15 count.',
        'price': 1.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-015',
        'stock': 100,
        'rating': 4.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '58.png',
    },
    {
        'name': 'Sunlight Kids Wet Wipes (Ladybug)',
        'slug': 'sunlight-kids-wet-wipes-ladybug',
        'description': 'Gentle alcohol-free, pH-balanced wet wipes for kids featuring a cheerful ladybug character, 15 count.',
        'price': 1.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-016',
        'stock': 110,
        'rating': 3.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '59.png',
    },
    {
        'name': 'Sunlight Kids Wet Wipes (Penguin)',
        'slug': 'sunlight-kids-wet-wipes-penguin',
        'description': 'Gentle alcohol-free, pH-balanced wet wipes for kids featuring a playful penguin character, 15 count.',
        'price': 1.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-017',
        'stock': 120,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '60.png',
    },
    {
        'name': 'Sunlight Kids Wet Wipes (Kitten)',
        'slug': 'sunlight-kids-wet-wipes-kitten',
        'description': 'Gentle alcohol-free, pH-balanced wet wipes for kids featuring an adorable kitten character, 15 count.',
        'price': 1.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-018',
        'stock': 130,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '61.png',
    },
    {
        'name': 'Sunlight Kids Wet Wipes Baby Pack (15+2)',
        'slug': 'sunlight-kids-wet-wipes-baby-pack-15-2',
        'description': 'Gentle wet wipes for babies and kids in a pastel heart-print pouch, 15+2 count bonus pack.',
        'price': 1.25,
        'old_price': 1.52,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'badge': '-18%',
        'sku': 'BKW-019',
        'stock': 140,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '63.png',
    },
    {
        'name': 'Sunlight Baby Wet Wipes Sensitive & Soft',
        'slug': 'sunlight-baby-wet-wipes-sensitive-soft',
        'description': 'Sensitive and soft baby wet wipes designed for delicate skin, 15+2 count pack.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-020',
        'stock': 150,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '64.png',
    },
    {
        'name': 'Sunlight Wet Towel Chamomile',
        'slug': 'sunlight-wet-towel-chamomile',
        'description': 'Alcohol-free and paraben-free chamomile-scented wet towels for babies, 15+2 count.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-021',
        'stock': 40,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '66.png',
    },
    {
        'name': 'Sunlight Wet Wipe Single Sachet (Orange Pattern)',
        'slug': 'sunlight-wet-wipe-single-sachet-orange',
        'description': 'Individually wrapped Sunlight wet wipe sachet with an orange oriental pattern, ideal for on-the-go use.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-036',
        'stock': 50,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '67.png',
    },
    {
        'name': 'Sunlight Wet Wipe Single Sachet (Blue Pattern)',
        'slug': 'sunlight-wet-wipe-single-sachet-blue-pattern',
        'description': 'Individually wrapped Sunlight wet wipe sachet with a blue oriental pattern, ideal for on-the-go use.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-037',
        'stock': 60,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '68.png',
    },
    {
        'name': 'Sunlight Wet Toilet Paper Peach',
        'slug': 'sunlight-wet-toilet-paper-peach',
        'description': 'Flushable and biodegradable peach-scented wet toilet paper, 30 sheets.',
        'price': 5.5,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-038',
        'stock': 70,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '69.png',
    },
    {
        'name': 'Sunlight Wet Toilet Paper Rose',
        'slug': 'sunlight-wet-toilet-paper-rose',
        'description': 'Flushable and biodegradable rose-scented wet toilet paper, 30 sheets.',
        'price': 5.5,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-039',
        'stock': 80,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '70.png',
    },
    {
        'name': 'Comforta Herbal Aroma Sanitary Pads — Aloe & Lavender, Mega Pack of 60',
        'slug': 'comforta-herbal-aroma-sanitary-pads-aloe',
        'description': 'Scented daily sanitary pads infused with aloe vera and lavender for lasting comfort and freshness, mega value pack of 60.',
        'price': 46,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-001',
        'stock': 70,
        'rating': 4.1,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '131.png',
    },
    {
        'name': 'Comforta Herbal Aroma Sanitary Pads — Aloe & Lavender, 20-Count',
        'slug': 'comforta-herbal-aroma-sanitary-pads-aloe-2',
        'description': 'Scented daily sanitary pads infused with aloe vera and lavender for lasting comfort and freshness, 20-pack.',
        'price': 27,
        'old_price': 32.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'badge': '-17%',
        'sku': 'FEM-002',
        'stock': 80,
        'rating': 4.2,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '132.png',
    },
    {
        'name': 'Comforta Herbal Aroma Sanitary Pads — Sea Buckthorn & Propolis, Mega Pack of 60',
        'slug': 'comforta-herbal-aroma-sanitary-pads-sea',
        'description': 'Scented daily sanitary pads infused with sea buckthorn and propolis for a fresh, comfortable feel, mega value pack of 60.',
        'price': 46,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-003',
        'stock': 90,
        'rating': 4.3,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '133.png',
    },
    {
        'name': 'Comforta Herbal Aroma Sanitary Pads — Sea Buckthorn & Propolis, 20-Count',
        'slug': 'comforta-herbal-aroma-sanitary-pads-sea-2',
        'description': 'Scented daily sanitary pads infused with sea buckthorn and propolis for a fresh, comfortable feel, 20-pack.',
        'price': 27,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-004',
        'stock': 100,
        'rating': 4.4,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '134.png',
    },
    {
        'name': 'Comforta Herbal Aroma Sanitary Pads — Chamomile & Calendula, Mega Pack of 60',
        'slug': 'comforta-herbal-aroma-sanitary-pads',
        'description': 'Scented daily sanitary pads infused with chamomile and calendula for gentle comfort and freshness, mega value pack of 60.',
        'price': 46,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-005',
        'stock': 110,
        'rating': 4.5,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '135.png',
    },
    {
        'name': 'Comforta Herbal Aroma Sanitary Pads — Chamomile & Calendula, 20-Count',
        'slug': 'comforta-herbal-aroma-sanitary-pads-2',
        'description': 'Scented daily sanitary pads infused with chamomile and calendula for gentle comfort and freshness, 20-pack.',
        'price': 27,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'badge': 'New',
        'sku': 'FEM-006',
        'stock': 120,
        'rating': 4.6,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '136.png',
    },
    {
        'name': 'Comforta Classic Sanitary Pads, 10-Count',
        'slug': 'comforta-classic-sanitary-pads-10-count',
        'description': 'Everyday sanitary napkins with a quick-dry mesh surface and up to 100% leak protection, normal absorbency, 10-pack.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-007',
        'stock': 130,
        'rating': 4.7,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '137.png',
    },
    {
        'name': 'Comforta Night Classic Sanitary Pads, 10-Count',
        'slug': 'comforta-night-classic-sanitary-pads-10-count',
        'description': 'Extra-absorbent overnight sanitary napkins with a quick-dry mesh surface and up to 100% leak protection, 10-pack.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-008',
        'stock': 140,
        'rating': 4.8,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '138.png',
    },
    {
        'name': 'Comforta Classic Soft Sanitary Pads, 10-Count',
        'slug': 'comforta-classic-soft-sanitary-pads-10-count',
        'description': 'Everyday sanitary napkins with a cotton-soft cover and quick-dry surface, normal absorbency, 10-pack.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-009',
        'stock': 150,
        'rating': 4.9,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '139.png',
    },
    {
        'name': 'Comforta Night Classic Soft Sanitary Pads, 10-Count',
        'slug': 'comforta-night-classic-soft-sanitary-pads-10',
        'description': 'Overnight sanitary napkins with a cotton-soft cover and maximum absorbency, up to 100% leak protection, 10-pack.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-010',
        'stock': 40,
        'rating': 3.9,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '140.png',
    },
    {
        'name': 'Comforta Classic Sanitary Pads, Mega Pack of 20 (16+4)',
        'slug': 'comforta-classic-sanitary-pads-mega-pack-of',
        'description': 'Everyday sanitary napkins with a quick-dry mesh surface, value mega pack of 20 including 4 bonus pads.',
        'price': 27,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-011',
        'stock': 50,
        'rating': 4.0,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '141.png',
    },
    {
        'name': 'Comforta Night Classic Sanitary Pads, Mega Pack of 20 (16+4)',
        'slug': 'comforta-night-classic-sanitary-pads-mega',
        'description': 'Overnight sanitary napkins with maximum absorbency and leak protection, value mega pack of 20 including 4 bonus pads.',
        'price': 27,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-012',
        'stock': 60,
        'rating': 4.1,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '142.png',
    },
    {
        'name': 'Comforta Classic Soft Sanitary Pads, Mega Pack of 20 (16+4)',
        'slug': 'comforta-classic-soft-sanitary-pads-mega',
        'description': 'Everyday sanitary napkins with a cotton-soft cover, value mega pack of 20 including 4 bonus pads.',
        'price': 27,
        'old_price': 32.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'badge': '-17%',
        'sku': 'FEM-013',
        'stock': 70,
        'rating': 4.2,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '143.png',
    },
    {
        'name': 'Comforta Night Classic Soft Sanitary Pads, Mega Pack of 20 (16+4)',
        'slug': 'comforta-night-classic-soft-sanitary-pads',
        'description': 'Overnight sanitary napkins with a cotton-soft cover and maximum absorbency, value mega pack of 20 including 4 bonus pads.',
        'price': 27,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-014',
        'stock': 80,
        'rating': 4.3,
        'is_popular': True,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '144.png',
    },
    {
        'name': 'Natural Fresh Infante Baby Wet Wipes, 120-Count',
        'slug': 'natural-fresh-infante-baby-wet-wipes-120',
        'description': 'Alcohol-free baby wet wipes with a neutral pH and cloud-soft texture that gently cleanse and refresh delicate skin, 120 pieces.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-022',
        'stock': 50,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '157.png',
    },
    {
        'name': 'Natural Fresh Infante Baby Wet Wipes, 72-Count',
        'slug': 'natural-fresh-infante-baby-wet-wipes-72-count',
        'description': 'Alcohol-free baby wet wipes with a neutral pH and cloud-soft texture that gently cleanse and refresh delicate skin, 72 pieces.',
        'price': 3.8,
        'old_price': 4.58,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'badge': '-17%',
        'sku': 'BKW-023',
        'stock': 60,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '158.png',
    },
    {
        'name': 'Natural Fresh Piccolo Baby Wet Wipes, 120-Count',
        'slug': 'natural-fresh-piccolo-baby-wet-wipes-120',
        'description': 'Alcohol-free baby wet wipes with a neutral pH and cloud-soft texture, gentle for delicate baby skin, 120 pieces.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-024',
        'stock': 70,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '159.png',
    },
    {
        'name': 'Natural Fresh Piccolo Baby Wet Wipes, 72-Count',
        'slug': 'natural-fresh-piccolo-baby-wet-wipes-72-count',
        'description': 'Alcohol-free baby wet wipes with a neutral pH and cloud-soft texture, gentle for delicate baby skin, 72 pieces.',
        'price': 3.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-025',
        'stock': 80,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '160.png',
    },
    {
        'name': 'Natural Fresh Mamma Wet Wipes, Extra Pack 72-Count',
        'slug': 'natural-fresh-mamma-wet-wipes-extra-pack-72',
        'description': 'Gentle family wet wipes for mother and baby, extra-value pack of 72 pieces.',
        'price': 3.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'badge': 'New',
        'sku': 'BKW-026',
        'stock': 90,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '162.png',
    },
    {
        'name': 'Natural Fresh Insieme Wet Wipes, Extra Pack 120-Count',
        'slug': 'natural-fresh-insieme-wet-wipes-extra-pack',
        'description': 'Gentle family wet wipes for everyday cleansing, extra-value pack of 120 pieces.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-027',
        'stock': 100,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '163.png',
    },
    {
        'name': 'Natural Fresh Insieme Wet Wipes, Extra Pack 72-Count',
        'slug': 'natural-fresh-insieme-wet-wipes-extra-pack-2',
        'description': 'Gentle family wet wipes for everyday cleansing, extra-value pack of 72 pieces.',
        'price': 3.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-028',
        'stock': 110,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '164.png',
    },
    {
        'name': 'Natural Fresh Chamomile Wet Wipes, 120-Count',
        'slug': 'natural-fresh-chamomile-wet-wipes-120-count',
        'description': 'Alcohol- and paraben-free wet wipes scented with chamomile for gentle everyday cleansing, 120 pieces.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'UNW-040',
        'stock': 120,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '165.png',
    },
    {
        'name': 'Natural Fresh Chamomile Wet Wipes, 72-Count',
        'slug': 'natural-fresh-chamomile-wet-wipes-72-count',
        'description': 'Alcohol- and paraben-free wet wipes scented with chamomile for gentle everyday cleansing, 72 pieces.',
        'price': 3.8,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'UNW-041',
        'stock': 130,
        'rating': 4.9,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '166.png',
    },
    {
        'name': 'Natural Fresh Rose Wet Towels, 120-Count',
        'slug': 'natural-fresh-rose-wet-towels-120-count',
        'description': 'pH-balanced, alcohol- and paraben-free wet wipes enriched with vitamin E and rose fragrance, 120 pieces.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'UNW-042',
        'stock': 140,
        'rating': 3.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '167.png',
    },
    {
        'name': 'Natural Fresh Rose Wet Towels, 72-Count',
        'slug': 'natural-fresh-rose-wet-towels-72-count',
        'description': 'pH-balanced, alcohol- and paraben-free wet wipes enriched with vitamin E and rose fragrance, 72 pieces.',
        'price': 3.8,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'UNW-043',
        'stock': 150,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '168.png',
    },
    {
        'name': 'Natural Fresh Baby Fish Wet Wipes, 120-Count',
        'slug': 'natural-fresh-baby-fish-wet-wipes-120-count',
        'description': 'Baby wet wipes in a playful fish-print pack for gentle daily cleansing of delicate skin, 120 pieces.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'badge': 'New',
        'sku': 'BKW-029',
        'stock': 40,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '169.png',
    },
    {
        'name': 'Natural Fresh Kids Kittens Wet Wipes, 120-Count',
        'slug': 'natural-fresh-kids-kittens-wet-wipes-120',
        'description': "Kids' wet wipes in a charming kitten-print pack for gentle daily cleansing, 120 pieces.",
        'price': 5.9,
        'old_price': 7.11,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'badge': '-17%',
        'sku': 'BKW-030',
        'stock': 50,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '170.png',
    },
    {
        'name': 'Natural Fresh Kids Forest Wet Wipes, 120-Count',
        'slug': 'natural-fresh-kids-forest-wet-wipes-120-count',
        'description': "Kids' wet wipes in a woodland-animal-print pack for gentle daily cleansing, 120 pieces.",
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-031',
        'stock': 60,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '171.png',
    },
    {
        'name': 'Natural Fresh Baby Flower Meadow Wet Wipes, 120-Count',
        'slug': 'natural-fresh-baby-flower-meadow-wet-wipes',
        'description': 'Baby wet wipes in a bird-and-flower-print pack for gentle daily cleansing of delicate skin, 120 pieces.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-032',
        'stock': 70,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '172.png',
    },
    {
        'name': 'Natural Fresh Universal Wet Wipes 120pcs',
        'slug': 'natural-fresh-universal-wet-wipes-120pcs',
        'description': 'Multi-purpose wet wipes in a resealable 120-count pack for everyday cleaning and freshening.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'UNW-044',
        'stock': 80,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '173.png',
    },
    {
        'name': 'Natural Fresh Universal Wet Wipes 120pcs (Floral Print)',
        'slug': 'natural-fresh-universal-wet-wipes-120pcs-2',
        'description': 'Multi-purpose wet wipes in a resealable 120-count pack with a colorful floral and feather design.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'UNW-045',
        'stock': 90,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '174.png',
    },
    {
        'name': 'Natural Fresh Universal Wet Wipes 120pcs, Fragrance-Free',
        'slug': 'natural-fresh-universal-wet-wipes-120pcs-3',
        'description': 'Fragrance-free multi-purpose wet wipes in a resealable 120-count pack with a purple floral and bird print design.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'UNW-046',
        'stock': 100,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '175.png',
    },
    {
        'name': 'Natural Fresh Malyshka Ultra Baby Wet Wipes 100pcs',
        'slug': 'natural-fresh-malyshka-ultra-baby-wet-wipes',
        'description': 'Extra-thick pH-balanced baby wet wipes for girls, free from alcohol and parabens, 100-count pack.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'badge': 'New',
        'sku': 'BKW-033',
        'stock': 110,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '177.png',
    },
    {
        'name': 'Natural Fresh Malysh Ultra Baby Wet Wipes 100pcs',
        'slug': 'natural-fresh-malysh-ultra-baby-wet-wipes',
        'description': 'Extra-thick pH-balanced baby wet wipes for boys, free from alcohol and parabens, 100-count pack.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-034',
        'stock': 120,
        'rating': 4.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '178.png',
    },
    {
        'name': 'Natural Fresh Family Ultra Wet Wipes 100pcs',
        'slug': 'natural-fresh-family-ultra-wet-wipes-100pcs',
        'description': 'Extra-thick pH-balanced family wet wipes, free from alcohol and parabens, 100-count pack.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-035',
        'stock': 130,
        'rating': 3.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '179.png',
    },
    {
        'name': 'Natural Fresh Baby Sea XXL Wet Wipes 70pcs',
        'slug': 'natural-fresh-baby-sea-xxl-wet-wipes-70pcs',
        'description': 'Extra-large (25x25cm) baby wet wipes with D-panthenol, towel-sized, featuring a playful sea-creature design, 70-count pack.',
        'price': 7.65,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-036',
        'stock': 140,
        'rating': 4.0,
        'is_featured': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '180.png',
    },
    {
        'name': 'Natural Fresh Baby Fish XXL Wet Wipes 70pcs',
        'slug': 'natural-fresh-baby-fish-xxl-wet-wipes-70pcs',
        'description': 'Extra-large (25x25cm) baby wet wipes enriched with vitamin E, towel-sized, featuring a colorful fish and octopus design, 70-count pack.',
        'price': 7.65,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-037',
        'stock': 150,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '181.png',
    },
    {
        'name': 'Natural Fresh Antibacterial Wet Wipes 15pcs (Green)',
        'slug': 'natural-fresh-antibacterial-wet-wipes-15pcs',
        'description': 'Refreshing antibacterial wet wipes, alcohol- and paraben-free with no added fragrance, compact 15-count pack.',
        'price': 1.0,
        'old_price': 1.22,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'badge': '-18%',
        'sku': 'UNW-047',
        'stock': 40,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '182.png',
    },
    {
        'name': 'Natural Fresh Antibacterial Wet Wipes 15pcs (Coral)',
        'slug': 'natural-fresh-antibacterial-wet-wipes-15pcs-2',
        'description': 'Refreshing antibacterial wet wipes, alcohol- and paraben-free with no added fragrance, compact 15-count pack.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'UNW-048',
        'stock': 50,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '183.png',
        'gallery_files': ['184.png', '185.png'],
    },
    {
        'name': 'Natural Fresh Wet Wipes SuperMini (8 x 9 pcs)',
        'slug': 'natural-fresh-wet-wipes-supermini-8x9-pcs',
        'description': 'A bundle of 8 individually wrapped mini travel packs (9 wipes each, 140x150mm) with a playful teddy bear print, in blue or pink — handy for diaper bags, strollers, and pockets.',
        'price': 4.7,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-070',
        'stock': 45,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '342.jpg',
    },
    {
        'name': 'Natural Fresh Mamma Wet Wipes 15+2pcs',
        'slug': 'natural-fresh-mamma-wet-wipes-15-2pcs',
        'description': 'Gentle wet wipes for mother and baby in a floral pink-themed 15+2 pack.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'badge': 'New',
        'sku': 'BKW-038',
        'stock': 60,
        'rating': 4.4,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '186.png',
    },
    {
        'name': 'Natural Fresh Insieme Wet Wipes 15+2pcs',
        'slug': 'natural-fresh-insieme-wet-wipes-15-2pcs',
        'description': 'Gentle wet wipes for mother and baby in a teal poppy-floral 15+2 pack.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-039',
        'stock': 70,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '187.png',
    },
    {
        'name': 'Natural Fresh Piccolo Baby Wet Wipes 15+2pcs',
        'slug': 'natural-fresh-piccolo-baby-wet-wipes-15-2pcs',
        'description': 'Baby wet wipes with a neutral-pH formula that cleanses and refreshes gently, 15+2 pack.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-040',
        'stock': 80,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '188.png',
    },
    {
        'name': 'Rio Premium Cream Wet Wipes 120pcs',
        'slug': 'rio-premium-cream-wet-wipes-120pcs',
        'description': 'Cream-enriched baby wet wipes, pH-balanced and free from alcohol and parabens, 120-count pack.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-041',
        'stock': 50,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '198.png',
    },
    {
        'name': 'Rio Premium Cream Wet Wipes 72pcs',
        'slug': 'rio-premium-cream-wet-wipes-72pcs',
        'description': 'Cream-enriched baby wet wipes, pH-balanced and free from alcohol and parabens, 72-count pack.',
        'price': 3.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-042',
        'stock': 60,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '199.png',
    },
    {
        'name': 'Rio Baby Fox XL Wet Wipes 100pcs',
        'slug': 'rio-baby-fox-xl-wet-wipes-100pcs',
        'description': 'Extra-large baby wet wipes with vitamin E and provitamin B5, featuring a cute fox design, 100-count pack.',
        'price': 8.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-043',
        'stock': 70,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '201.png',
    },
    {
        'name': 'Rio Baby Fox XL Wet Wipes 70pcs',
        'slug': 'rio-baby-fox-xl-wet-wipes-70pcs',
        'description': 'Extra-large baby wet wipes with vitamin E and provitamin B5, featuring a cute fox design, 70-count pack.',
        'price': 6.5,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'badge': 'New',
        'sku': 'BKW-044',
        'stock': 80,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '202.png',
    },
    {
        'name': 'Rio Baby Panda XL Wet Wipes 100pcs',
        'slug': 'rio-baby-panda-xl-wet-wipes-100pcs',
        'description': 'Extra-large baby wet wipes with vitamin E and provitamin B5, featuring a cute red panda design, 100-count pack.',
        'price': 8.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-045',
        'stock': 90,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '203.png',
    },
    {
        'name': 'Rio Baby Panda XL Wet Wipes 70pcs',
        'slug': 'rio-baby-panda-xl-wet-wipes-70pcs',
        'description': 'Extra-large baby wet wipes with vitamin E and provitamin B5, featuring a cute red panda design, 70-count pack.',
        'price': 6.5,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-046',
        'stock': 100,
        'rating': 4.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '204.png',
    },
    {
        'name': 'Rio Pure Protect Baby Wet Wipes 100pcs',
        'slug': 'rio-pure-protect-baby-wet-wipes-100pcs',
        'description': 'Gentle baby wet wipes enriched with vitamin E for careful protection, tropical flamingo design, 100-count pack.',
        'price': 4.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-047',
        'stock': 110,
        'rating': 3.9,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '205.png',
    },
    {
        'name': 'Rio Pure Protect Baby Wet Wipes 80pcs',
        'slug': 'rio-pure-protect-baby-wet-wipes-80pcs',
        'description': 'Gentle baby wet wipes enriched with vitamin E for careful protection, tropical flamingo design, 80-count pack.',
        'price': 3.3,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-048',
        'stock': 120,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '206.png',
    },
    {
        'name': 'Rio Premium Baby Wet Wipes 100pcs',
        'slug': 'rio-premium-baby-wet-wipes-100pcs',
        'description': 'Baby wet wipes enriched with vitamin E for cleanliness and comfort, tropical toucan design, 100-count pack.',
        'price': 4.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-049',
        'stock': 130,
        'rating': 4.1,
        'is_featured': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '207.png',
    },
    {
        'name': 'Rio Premium Baby Wet Wipes 80pcs',
        'slug': 'rio-premium-baby-wet-wipes-80pcs',
        'description': 'Baby wet wipes enriched with vitamin E for cleanliness and comfort, tropical toucan design, 80-count pack.',
        'price': 3.3,
        'old_price': 3.98,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'badge': '-17%',
        'sku': 'BKW-050',
        'stock': 140,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '208.png',
    },
    {
        'name': 'Rio Ultimate Clean Baby Wet Wipes 100pcs',
        'slug': 'rio-ultimate-clean-baby-wet-wipes-100pcs',
        'description': 'Baby wet wipes enriched with vitamin E for absolute cleanliness, tropical floral design, 100-count pack.',
        'price': 4.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'badge': 'New',
        'sku': 'BKW-051',
        'stock': 150,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '209.png',
    },
    {
        'name': 'Rio Skin Care Baby Wet Wipes 100pcs',
        'slug': 'rio-skin-care-baby-wet-wipes-100pcs',
        'description': 'Baby wet wipes enriched with vitamin E and formulated for skin care, playful pink toucan design, 100-count pack.',
        'price': 4.0,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-052',
        'stock': 40,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '210.png',
    },
    {
        'name': 'Rio Pure Protect Baby Wet Wipes 40pcs',
        'slug': 'rio-pure-protect-baby-wet-wipes-40pcs',
        'description': 'Gentle baby wet wipes enriched with vitamin E for careful protection, tropical flamingo design, compact 40-count pack.',
        'price': 2.2,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-053',
        'stock': 50,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '211.png',
    },
    {
        'name': 'Rio Premium Baby Wet Wipes 40pcs',
        'slug': 'rio-premium-baby-wet-wipes-40pcs',
        'description': 'Baby wet wipes enriched with vitamin E for cleanliness and comfort, tropical toucan design, compact 40-count pack.',
        'price': 2.2,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-054',
        'stock': 60,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '212.png',
    },
    {
        'name': 'Rio Ultimate Clean Baby Wet Wipes 40pcs',
        'slug': 'rio-ultimate-clean-baby-wet-wipes-40pcs',
        'description': 'Baby wet wipes enriched with vitamin E for absolute cleanliness, tropical floral design, compact 40-count pack.',
        'price': 2.2,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-055',
        'stock': 70,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '213.png',
    },
    {
        'name': 'Rio Premium Cream Baby Wet Wipes 15+2pcs',
        'slug': 'rio-premium-cream-baby-wet-wipes-15-2pcs',
        'description': 'Cream-enriched baby wet wipes with vitamin E and provitamin B5, pH-balanced travel pack of 15+2.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-056',
        'stock': 80,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '215.png',
    },
    {
        'name': 'Rio Pure Cream Baby Wet Wipes 15+2pcs',
        'slug': 'rio-pure-cream-baby-wet-wipes-15-2pcs',
        'description': 'Cream-enriched baby wet wipes with vitamin E and provitamin B5, pH-balanced travel pack of 15+2 featuring a cute bunny design.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-057',
        'stock': 90,
        'rating': 4.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '216.png',
    },
    {
        'name': 'Rio Care Wet Wipes 15+2 pcs',
        'slug': 'rio-care-wet-wipes-15-2-pcs',
        'description': 'Alcohol- and paraben-free wet wipes with chamomile and cream extract, pH-balanced 5.5, featuring a fox mascot for kids.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'badge': 'New',
        'sku': 'BKW-058',
        'stock': 100,
        'rating': 3.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '217.png',
    },
    {
        'name': 'Rio Exotic Fruits Lulo Wet Wipes 15 pcs',
        'slug': 'rio-exotic-fruits-lulo-wet-wipes-15-pcs',
        'description': 'Alcohol- and paraben-free wet wipes scented with exotic lulo fruit, pH 5.5 balanced.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'rio',
        'sku': 'UNW-049',
        'stock': 110,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '218.png',
    },
    {
        'name': 'Rio Exotic Fruits Passiflora Wet Wipes 15 pcs',
        'slug': 'rio-exotic-fruits-passiflora-wet-wipes-15-pcs',
        'description': 'Alcohol- and paraben-free wet wipes scented with passion fruit, pH 5.5 balanced.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'rio',
        'sku': 'UNW-050',
        'stock': 120,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '219.png',
    },
    {
        'name': 'Rio Exotic Fruits Mangosteen Wet Wipes 15 pcs',
        'slug': 'rio-exotic-fruits-mangosteen-wet-wipes-15-pcs',
        'description': 'Alcohol- and paraben-free wet wipes scented with mangosteen fruit, pH 5.5 balanced.',
        'price': 1.0,
        'old_price': 1.22,
        'category_slug': 'universal-wipes',
        'brand_slug': 'rio',
        'badge': '-18%',
        'sku': 'UNW-051',
        'stock': 130,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '220.png',
    },
    {
        'name': 'Rio Exotic Fruits Momordica Wet Wipes 15 pcs',
        'slug': 'rio-exotic-fruits-momordica-wet-wipes-15-pcs',
        'description': 'Alcohol- and paraben-free wet wipes scented with momordica fruit, pH 5.5 balanced.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'rio',
        'sku': 'UNW-052',
        'stock': 140,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '221.png',
    },
    {
        'name': 'Rio Exotic Flowers Plumeria Wet Wipes 15 pcs',
        'slug': 'rio-exotic-flowers-plumeria-wet-wipes-15-pcs',
        'description': 'Alcohol- and paraben-free wet wipes scented with plumeria flower, pH 5.5 balanced.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'rio',
        'sku': 'UNW-053',
        'stock': 150,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '222.png',
    },
    {
        'name': 'Rio Exotic Flowers Puya Wet Wipes 15 pcs',
        'slug': 'rio-exotic-flowers-puya-wet-wipes-15-pcs',
        'description': 'Alcohol- and paraben-free wet wipes scented with exotic puya flower, pH 5.5 balanced.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'rio',
        'sku': 'UNW-054',
        'stock': 40,
        'rating': 4.5,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '223.png',
    },
    {
        'name': 'Rio Exotic Flowers Cosmea Wet Wipes 15 pcs',
        'slug': 'rio-exotic-flowers-cosmea-wet-wipes-15-pcs',
        'description': 'Alcohol- and paraben-free wet wipes scented with cosmea flower, pH 5.5 balanced.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'rio',
        'badge': 'New',
        'sku': 'UNW-055',
        'stock': 50,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '224.png',
    },
    {
        'name': 'Rio Exotic Flowers Freesia Wet Wipes 15 pcs',
        'slug': 'rio-exotic-flowers-freesia-wet-wipes-15-pcs',
        'description': 'Alcohol- and paraben-free wet wipes scented with freesia flower, pH 5.5 balanced.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'rio',
        'sku': 'UNW-070',
        'stock': 60,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '341.jpg',
    },
    {
        'name': 'Peri Classic Normal Sanitary Pads Mega Pack, 16+4 pcs',
        'slug': 'peri-classic-normal-sanitary-pads-mega-pack',
        'description': 'Normal-absorbency sanitary pads with a mesh top surface and 5 layers of protection, 16+4-count mega pack.',
        'price': 21.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'sku': 'FEM-037',
        'stock': 50,
        'rating': 4.8,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '248.png',
    },
    {
        'name': 'Peri Classic Night Sanitary Pads Mega Pack, 16+4 pcs',
        'slug': 'peri-classic-night-sanitary-pads-mega-pack',
        'description': 'Night-use sanitary pads with a mesh top surface and 5 layers of protection for overnight coverage, 16+4-count mega pack.',
        'price': 21.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'sku': 'FEM-038',
        'stock': 60,
        'rating': 4.9,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '249.png',
    },
    {
        'name': 'Peri Classic Soft Normal Sanitary Pads Mega Pack, 16+4 pcs',
        'slug': 'peri-classic-soft-normal-sanitary-pads-mega',
        'description': 'Normal-absorbency sanitary pads with a soft cotton-like top surface and 5 layers of protection, 16+4-count mega pack.',
        'price': 21.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'sku': 'FEM-039',
        'stock': 70,
        'rating': 3.9,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '250.png',
    },
    {
        'name': 'Peri Classic Soft Night Sanitary Pads Mega Pack, 16+4 pcs',
        'slug': 'peri-classic-soft-night-sanitary-pads-mega',
        'description': 'Night-use sanitary pads with a soft cotton-like top surface and 5 layers of protection for overnight coverage, 16+4-count mega pack.',
        'price': 21.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'sku': 'FEM-040',
        'stock': 80,
        'rating': 4.0,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '251.png',
    },
    {
        'name': 'Peri Classic Normal Sanitary Pads, 10 pcs',
        'slug': 'peri-classic-normal-sanitary-pads-10-pcs',
        'description': 'Normal-absorbency sanitary pads with a mesh top surface and 5 layers of protection, 10-count pack.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'badge': 'New',
        'sku': 'FEM-041',
        'stock': 90,
        'rating': 4.1,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '252.png',
    },
    {
        'name': 'Peri Classic Night Sanitary Pads, 10 pcs',
        'slug': 'peri-classic-night-sanitary-pads-10-pcs',
        'description': 'Night-use sanitary pads with a mesh top surface and 5 layers of protection for overnight coverage, 10-count pack.',
        'price': 13.5,
        'old_price': 16,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'badge': '-16%',
        'sku': 'FEM-042',
        'stock': 100,
        'rating': 4.2,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '253.png',
    },
    {
        'name': 'Peri Classic Soft Normal Sanitary Pads, 10 pcs',
        'slug': 'peri-classic-soft-normal-sanitary-pads-10-pcs',
        'description': 'Normal-absorbency sanitary pads with a soft cotton-like top surface and 5 layers of protection, 10-count pack.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'sku': 'FEM-043',
        'stock': 110,
        'rating': 4.3,
        'is_featured': True,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '254.png',
    },
    {
        'name': 'Peri Classic Soft Night Sanitary Pads, 10 pcs',
        'slug': 'peri-classic-soft-night-sanitary-pads-10-pcs',
        'description': 'Night-use sanitary pads with a soft cotton-like top surface and 5 layers of protection for overnight coverage, 10-count pack.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'sku': 'FEM-044',
        'stock': 120,
        'rating': 4.4,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '255.png',
    },
    {
        'name': 'Peri Compact Soft Normal Sanitary Pads, 10 pcs',
        'slug': 'peri-compact-soft-normal-sanitary-pads-10-pcs',
        'description': 'Compact, normal-absorbency sanitary pads with a soft cotton-like top surface and 5 layers of protection, 10-count pack.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'sku': 'FEM-045',
        'stock': 130,
        'rating': 4.5,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'image_file': '256.png',
    },
    {
        'name': 'Sunlight Universal XXL Wet Wipes – Display Box (8 x 9 pcs)',
        'slug': 'sunlight-universal-xxl-wet-wipes-display-box',
        'description': 'A retail display box containing 8 individually wrapped packs of Sunlight Universal XXL wet wipes, 9 wipes per pack.',
        'price': 8.0,
        'old_price': 9.64,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': '-17%',
        'sku': 'UNW-062',
        'stock': 70,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '287.png',
    },
    {
        'name': 'Sunlight Universal Flat Mop',
        'slug': 'sunlight-universal-flat-mop',
        'description': 'A collapsible, universal flat mop by Sunlight designed for wet floor cleaning; this is a reusable cleaning tool, not a disposable wipe or tissue.',
        'price': 16.0,
        'category_slug': 'household-cleaning',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'HCL-012',
        'stock': 80,
        'rating': 4.3,
        'ingredients': 'Non-woven viscose-blend fabric, mild surfactant',
        'image_file': '288.png',
    },
    {
        'name': 'Sunlight XXL Wet Wipes (50 pcs)',
        'slug': 'sunlight-xxl-wet-wipes-50-pcs',
        'description': 'Sunlight XXL wet wipes, packaged with floor-cleaning imagery, provide a large 50-count pack for household surface wiping.',
        'price': 6.5,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-063',
        'stock': 90,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '289.png',
    },
    {
        'name': 'Natural Fresh Infante Baby Wet Wipes 72-Pack (Twin)',
        'slug': 'natural-fresh-infante-baby-wet-wipes-72-pack',
        'description': '72-count pack of gentle wet wipes for babies, alcohol-free and suitable for sensitive skin.',
        'price': 3.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'badge': 'New',
        'sku': 'BKW-059',
        'stock': 140,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '332.png',
    },
    {
        'name': 'Natural Fresh Piccolo Baby Wet Wipes 72-Pack (Twin)',
        'slug': 'natural-fresh-piccolo-baby-wet-wipes-72-pack',
        'description': '72-count pack of gentle wet wipes for baby girls, alcohol-free and suitable for sensitive skin.',
        'price': 3.8,
        'old_price': 4.58,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'badge': '-17%',
        'sku': 'BKW-060',
        'stock': 150,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '333.png',
    },
    {
        'name': 'Natural Fresh Mamma Extra Pack Wet Wipes (Twin Display)',
        'slug': 'natural-fresh-mamma-extra-pack-wet-wipes',
        'description': 'Extra-large value packs of gentle wet wipes for mother and baby use.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-061',
        'stock': 40,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '334.png',
    },
    {
        'name': 'Natural Fresh Insieme Extra Pack Wet Wipes (Twin Display)',
        'slug': 'natural-fresh-insieme-extra-pack-wet-wipes',
        'description': 'Extra-large value packs of gentle wet wipes for the whole family.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-062',
        'stock': 50,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '335.png',
    },
    {
        'name': 'Sunlight Universal XXL Wet Towels (100 pcs)',
        'slug': 'sunlight-universal-xxl-wet-towels-100-pcs',
        'description': 'Extra-large universal wet towels for daily personal hygiene, sized 250x250mm and packed 100 to a pack.',
        'price': 4.5,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-064',
        'stock': 80,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': 'photo_2024-09-19_17-15-49.jpg',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes Violet Network (120 pcs)',
        'slug': 'sunlight-antibacterial-wet-wipes-violet-2',
        'description': 'Antibacterial wet wipes offering maximum protection from bacteria, in a violet network-pattern pack of 120.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'UNW-065',
        'stock': 90,
        'rating': 4.8,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': 'IMG_0036.png',
    },
    {
        'name': 'Rio Universal Wet Wipes (120 pcs)',
        'slug': 'rio-universal-wet-wipes-120-pcs',
        'description': 'Alcohol- and paraben-free universal wet wipes, pH 5.5 balanced and unscented, 120 count.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'rio',
        'sku': 'UNW-066',
        'stock': 100,
        'rating': 4.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '200.png',
    },
    {
        'name': 'Natural Fresh Universal Ultra Wet Wipes (100 pcs)',
        'slug': 'natural-fresh-universal-ultra-wet-wipes-100',
        'description': 'Extra-thick unscented universal wet wipes in a resealable 100-count pack.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'UNW-067',
        'stock': 110,
        'rating': 3.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '176.png',
    },
    {
        'name': 'Sunlight Sensitive & Soft Universal Wet Wipes with Cream (120 pcs)',
        'slug': 'sunlight-sensitive-soft-universal-wet-wipes',
        'description': 'Cream-enriched, fragrance-free universal wet wipes, alcohol-free and pH-balanced, in a 120-count Extra Pack.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-068',
        'stock': 120,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '9.png',
    },
    {
        'name': 'Sunlight Kids Ladybug Wet Wipes (15+2 pcs)',
        'slug': 'sunlight-kids-ladybug-wet-wipes-15-2-pcs',
        'description': "Gentle alcohol-free, pH-balanced kids' wet wipes featuring a cheerful ladybug design, 15+2 count.",
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-063',
        'stock': 130,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '8.png',
        'gallery_files': ['62.png'],
    },
    {
        'name': 'Sunlight Chamomile Baby Wet Wipes (15+2 pcs)',
        'slug': 'sunlight-chamomile-baby-wet-wipes-15-2-pcs',
        'description': 'Alcohol- and paraben-free chamomile-scented baby wet wipes, 15+2 count.',
        'price': 1.25,
        'old_price': 1.52,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'badge': '-18%',
        'sku': 'BKW-064',
        'stock': 140,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '65.png',
    },
    {
        'name': 'Natural Fresh Piccolo Baby Wet Wipes (15+2 pcs)',
        'slug': 'natural-fresh-piccolo-baby-wet-wipes-15-2-pcs',
        'description': 'Gentle alcohol-free baby wet wipes with a neutral pH, featuring an adorable teddy bear design, 15+2 count.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-065',
        'stock': 150,
        'rating': 4.3,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '1.png',
    },
    {
        'name': 'Natural Fresh Chamomile Wet Wipes Twin Pack (2x72 pcs)',
        'slug': 'natural-fresh-chamomile-wet-wipes-twin-pack',
        'description': 'Chamomile-scented baby wet wipes in a convenient twin pack of two 72-count pouches.',
        'price': 7.6,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'badge': 'New',
        'sku': 'BKW-066',
        'stock': 40,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '336.png',
    },
    {
        'name': 'Natural Fresh Mamma Wet Wipes Extra Pack (120 pcs)',
        'slug': 'natural-fresh-mamma-wet-wipes-extra-pack-120',
        'description': 'Gentle wet wipes for mother and baby in an extra-large value pack of 120.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-067',
        'stock': 50,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '161.png',
    },
    {
        'name': 'Natural Fresh Infante Baby Wet Wipes (15+2 pcs)',
        'slug': 'natural-fresh-infante-baby-wet-wipes-15-2-pcs',
        'description': 'Alcohol-free baby wet wipes with a neutral pH, featuring a soft blue cloud design, 15+2 count.',
        'price': 1.25,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-068',
        'stock': 60,
        'rating': 4.6,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '189.png',
    },
    {
        'name': 'Rio Skin Care Baby Wet Wipes (40 pcs)',
        'slug': 'rio-skin-care-baby-wet-wipes-40-pcs',
        'description': 'Vitamin E enriched baby wet wipes formulated for skin care, 40 count.',
        'price': 2.2,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-069',
        'stock': 70,
        'rating': 4.7,
        'is_featured': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'image_file': '214.png',
    },
    {
        'name': 'Sunlight Parfum Man Wet Wipes (15 pcs, Splash)',
        'slug': 'sunlight-parfum-man-wet-wipes-15-pcs-splash',
        'description': 'Alcohol-free and paraben-free scented wet wipes for men in a blue water-splash pack of 15.',
        'price': 1.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'sku': 'UNW-069',
        'stock': 60,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'image_file': '48.png',
    },
    {
        'name': 'Sunlight Disposable Non-Woven Bed Sheet Roll, White (80x190cm)',
        'slug': 'sunlight-disposable-bed-sheet-roll-white',
        'description': 'A single roll of white disposable non-woven bed sheeting, 80x190cm per sheet, for hotels, spas, clinics, and salons.',
        'price': 38,
        'category_slug': 'horeca-disposables',
        'brand_slug': 'sunlight',
        'sku': 'HCR-001',
        'stock': 40,
        'rating': 4.3,
        'ingredients': 'Non-woven spunbond fabric',
        'image_file': '337.jpg',
    },
    {
        'name': 'Sunlight Disposable Non-Woven Bed Sheet Roll, Pink (80x190cm)',
        'slug': 'sunlight-disposable-bed-sheet-roll-pink',
        'description': 'A single roll of pink disposable non-woven bed sheeting, 80x190cm per sheet, for hotels, spas, clinics, and salons.',
        'price': 38,
        'category_slug': 'horeca-disposables',
        'brand_slug': 'sunlight',
        'sku': 'HCR-002',
        'stock': 40,
        'rating': 4.3,
        'ingredients': 'Non-woven spunbond fabric',
        'image_file': '338.jpg',
    },
    {
        'name': 'Sunlight Disposable Non-Woven Bed Sheet Roll, Blue (80x190cm)',
        'slug': 'sunlight-disposable-bed-sheet-roll-blue',
        'description': 'A single roll of blue disposable non-woven bed sheeting, 80x190cm per sheet, for hotels, spas, clinics, and salons.',
        'price': 38,
        'category_slug': 'horeca-disposables',
        'brand_slug': 'sunlight',
        'sku': 'HCR-003',
        'stock': 40,
        'rating': 4.3,
        'ingredients': 'Non-woven spunbond fabric',
        'image_file': '339.jpg',
    },
    {
        'name': 'Sunlight Disposable Non-Woven Bed Sheet Roll, Green (80x190cm)',
        'slug': 'sunlight-disposable-bed-sheet-roll-green',
        'description': 'A single roll of green disposable non-woven bed sheeting, 80x190cm per sheet, for hotels, spas, clinics, and salons.',
        'price': 38,
        'category_slug': 'horeca-disposables',
        'brand_slug': 'sunlight',
        'sku': 'HCR-004',
        'stock': 40,
        'rating': 4.3,
        'ingredients': 'Non-woven spunbond fabric',
        'image_file': '340.jpg',
    },
]
