"""Curated product catalog data (20 products spanning every category and brand),
generated from real GoldenSunlight product photography (see Mockups/ and
backend/seed_assets/products/). Every product carries a full Arabic translation
(name_ar/description_ar/ingredients_ar/badge_ar) alongside the English content.
Consumed by seed.py — do not hand-edit individual entries here; regenerate via
the cataloging pipeline if the source photos change."""

PRODUCTS_DATA = [
    # ─── Baby & Kids Wipes ─────────────────────────────────────
    {
        'name': 'Natural Fresh Infante Baby Wet Wipes',
        'name_ar': 'مناديل ناتشورال فريش المبللة للأطفال الرضع',
        'slug': 'natural-fresh-infante-baby-wet-wipes',
        'description': 'Gentle, alcohol-free baby wet wipes with a neutral pH, packed in a cloud-print pouch with a fun bear design for everyday infant care.',
        'description_ar': 'مناديل مبللة لطيفة للأطفال خالية من الكحول وبدرجة حموضة متعادلة، معبأة في كيس بطبعة سحابية بتصميم دب مرح للعناية اليومية بالرضع.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'natural-fresh',
        'sku': 'BKW-001',
        'stock': 40,
        'rating': 3.9,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، بانثينول، حمض الستريك، خالٍ من الكحول',
        'image_file': '2.png',
    },
    {
        'name': 'Rio Premium Baby Wet Wipes',
        'name_ar': 'مناديل ريو المبللة الفاخرة للأطفال',
        'slug': 'rio-premium-baby-wet-wipes',
        'description': 'Premium alcohol- and paraben-free baby wipes enriched with Vitamin E and Provitamin B5 for soft, gentle cleansing.',
        'description_ar': 'مناديل مبللة فاخرة للأطفال خالية من الكحول والبارابين، مدعّمة بفيتامين E وفيتامين B5 لتنظيف ناعم ولطيف.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'rio',
        'sku': 'BKW-002',
        'stock': 50,
        'rating': 4.0,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، بانثينول، حمض الستريك، خالٍ من الكحول',
        'image_file': '3.png',
    },
    {
        'name': 'Sunlight Kids Bunny Wet Wipes',
        'name_ar': 'مناديل صن لايت المبللة للأطفال بطراز الأرنب',
        'slug': 'sunlight-kids-bunny-wet-wipes',
        'description': "Alcohol-free, pH-balanced kids' wet wipes in a cheerful heart-print pack featuring a bunny character.",
        'description_ar': 'مناديل مبللة للأطفال خالية من الكحول ومتوازنة الحموضة، في عبوة مرحة بطبعة قلوب تحمل شخصية أرنب لطيفة.',
        'price': 5.9,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'badge_ar': 'جديد',
        'sku': 'BKW-003',
        'stock': 60,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، بانثينول، حمض الستريك، خالٍ من الكحول',
        'image_file': '4.png',
    },
    {
        'name': 'Sunlight Chamomile Baby Wet Wipes (72 pcs)',
        'name_ar': 'مناديل صن لايت المبللة للأطفال بالبابونج (72 منديلاً)',
        'slug': 'sunlight-chamomile-baby-wet-wipes-72-pcs',
        'description': 'Alcohol- and paraben-free chamomile-infused baby wet wipes at pH 5.5, in a daisy-print pack, 72 count.',
        'description_ar': 'مناديل مبللة للأطفال بخلاصة البابونج، خالية من الكحول والبارابين وبدرجة حموضة 5.5، في عبوة بطبعة الإقحوان، 72 منديلاً.',
        'price': 3.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-013',
        'stock': 90,
        'rating': 4.5,
        'is_popular': True,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، بانثينول، حمض الستريك، خالٍ من الكحول',
        'image_file': '20.png',
    },
    {
        'name': 'Sunlight Baby Wet Wipes – Bear & Zebra (120 pcs)',
        'name_ar': 'مناديل صن لايت المبللة للأطفال - دب وحمار وحشي (120 منديلاً)',
        'slug': 'sunlight-baby-wet-wipes-bear-zebra-120-pcs',
        'description': 'Alcohol- and paraben-free baby wet wipes at pH 5.5, packaged with a playful bear-and-zebra print, 120 count.',
        'description_ar': 'مناديل مبللة للأطفال خالية من الكحول والبارابين وبدرجة حموضة 5.5، معبأة بطبعة مرحة لدب وحمار وحشي، 120 منديلاً.',
        'price': 4.8,
        'category_slug': 'baby-kids-wipes',
        'brand_slug': 'sunlight',
        'sku': 'BKW-007',
        'stock': 150,
        'rating': 3.9,
        'ingredients': 'Purified water, glycerin, aloe vera extract, panthenol, citric acid, alcohol-free',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، بانثينول، حمض الستريك، خالٍ من الكحول',
        'image_file': '14.png',
        'gallery_files': ['15.png'],
    },

    # ─── Universal & Antibacterial Wipes ───────────────────────
    {
        'name': 'Sunlight Antibacterial Wet Wipes (Blue)',
        'name_ar': 'مناديل صن لايت المبللة المضادة للبكتيريا (أزرق)',
        'slug': 'sunlight-antibacterial-wet-wipes-blue',
        'description': 'Antibacterial wet wipes in blue packaging formulated to stop bacteria for everyday hygiene on the go.',
        'description_ar': 'مناديل مبللة مضادة للبكتيريا بعبوة زرقاء، مصمّمة للقضاء على البكتيريا للحفاظ على النظافة اليومية أثناء التنقل.',
        'price': 5.9,
        'old_price': 7.11,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'badge': '-17%',
        'badge_ar': '-17%',
        'sku': 'UNW-001',
        'stock': 70,
        'rating': 4.2,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، حمض الستريك، مادة حافظة خفيفة',
        'image_file': '5.png',
    },
    {
        'name': 'Sunlight Antibacterial Wet Wipes (Violet)',
        'name_ar': 'مناديل صن لايت المبللة المضادة للبكتيريا (بنفسجي)',
        'slug': 'sunlight-antibacterial-wet-wipes-violet',
        'description': 'Antibacterial wet wipes in violet packaging formulated to stop bacteria for everyday hygiene on the go.',
        'description_ar': 'مناديل مبللة مضادة للبكتيريا بعبوة بنفسجية، مصمّمة للقضاء على البكتيريا للحفاظ على النظافة اليومية أثناء التنقل.',
        'price': 5.9,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-002',
        'stock': 80,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، حمض الستريك، مادة حافظة خفيفة',
        'image_file': '5kara.png',
    },
    {
        'name': 'Sunlight Universal Wet Towels',
        'name_ar': 'مناديل صن لايت المبللة الشاملة',
        'slug': 'sunlight-universal-wet-towels',
        'description': 'Universal wet towels designed for daily personal hygiene, packaged 20 to a pack.',
        'description_ar': 'مناديل مبللة شاملة الاستخدام مصممة للنظافة الشخصية اليومية، معبأة 20 منديلاً في العبوة.',
        'price': 3.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-003',
        'stock': 100,
        'rating': 4.5,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، حمض الستريك، مادة حافظة خفيفة',
        'image_file': '7.png',
    },
    {
        'name': 'Sunlight Rose Wet Wipes (72 pcs)',
        'name_ar': 'مناديل صن لايت المبللة برائحة الورد (72 منديلاً)',
        'slug': 'sunlight-rose-wet-wipes-72-pcs',
        'description': 'Alcohol- and paraben-free rose-scented wet wipes at pH 5.5, packaged 72 to a pack.',
        'description_ar': 'مناديل مبللة برائحة الورد، خالية من الكحول والبارابين وبدرجة حموضة 5.5، معبأة 72 منديلاً في العبوة.',
        'price': 3.8,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-005',
        'stock': 110,
        'rating': 4.7,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، حمض الستريك، مادة حافظة خفيفة',
        'image_file': '22.png',
    },
    {
        'name': 'Sunlight Premium Wet Wipes (20 pcs)',
        'name_ar': 'مناديل صن لايت المبللة الفاخرة (20 منديلاً)',
        'slug': 'sunlight-premium-wet-wipes-20-pcs',
        'description': 'Premium wet wipes in a sleek black-and-orange geometric pack, 20 count.',
        'description_ar': 'مناديل مبللة فاخرة في عبوة أنيقة بتصميم هندسي أسود وبرتقالي، 20 منديلاً.',
        'price': 3.0,
        'category_slug': 'universal-wipes',
        'brand_slug': 'sunlight',
        'sku': 'UNW-008',
        'stock': 40,
        'rating': 4.1,
        'ingredients': 'Purified water, glycerin, aloe vera extract, citric acid, mild preservative',
        'ingredients_ar': 'ماء نقي، جليسرين، مستخلص الألوفيرا، حمض الستريك، مادة حافظة خفيفة',
        'image_file': '27.png',
    },

    # ─── Feminine Hygiene ───────────────────────────────────────
    {
        'name': 'Comforta Herbal Aroma Sanitary Pads — Aloe & Lavender, 20-Count',
        'name_ar': 'فوط كومفورتا الصحية العطرية العشبية - الألوة فيرا واللافندر (20 قطعة)',
        'slug': 'comforta-herbal-aroma-sanitary-pads-aloe-2',
        'description': 'Scented daily sanitary pads infused with aloe vera and lavender for lasting comfort and freshness, 20-pack.',
        'description_ar': 'فوط صحية يومية معطرة بخلاصة الألوة فيرا واللافندر لراحة ونقاء يدومان طويلاً، عبوة من 20 قطعة.',
        'price': 27,
        'old_price': 32.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'badge': '-17%',
        'badge_ar': '-17%',
        'sku': 'FEM-002',
        'stock': 80,
        'rating': 4.2,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'ingredients_ar': 'طبقة علوية غير منسوجة، لُب ماص فائق الامتصاص من البوليمر، طبقة خلفية قابلة للتهوية',
        'image_file': '132.png',
    },
    {
        'name': 'Comforta Classic Sanitary Pads, 10-Count',
        'name_ar': 'فوط كومفورتا الصحية الكلاسيكية (10 قطع)',
        'slug': 'comforta-classic-sanitary-pads-10-count',
        'description': 'Everyday sanitary napkins with a quick-dry mesh surface and up to 100% leak protection, normal absorbency, 10-pack.',
        'description_ar': 'فوط صحية للاستخدام اليومي بسطح شبكي سريع الجفاف وحماية من التسرب تصل إلى 100%، بامتصاص عادي، عبوة من 10 قطع.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-007',
        'stock': 130,
        'rating': 4.7,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'ingredients_ar': 'طبقة علوية غير منسوجة، لُب ماص فائق الامتصاص من البوليمر، طبقة خلفية قابلة للتهوية',
        'image_file': '137.png',
    },
    {
        'name': 'Comforta Night Classic Soft Sanitary Pads, Mega Pack of 20 (16+4)',
        'name_ar': 'فوط كومفورتا الصحية الليلية الكلاسيكية الناعمة - عبوة كبرى من 20 (16+4)',
        'slug': 'comforta-night-classic-soft-sanitary-pads',
        'description': 'Overnight sanitary napkins with a cotton-soft cover and maximum absorbency, value mega pack of 20 including 4 bonus pads.',
        'description_ar': 'فوط صحية ليلية بغطاء ناعم كالقطن وامتصاص فائق، عبوة كبرى موفرة من 20 قطعة تشمل 4 قطع مجانية إضافية.',
        'price': 27,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'comforta',
        'sku': 'FEM-014',
        'stock': 80,
        'rating': 4.3,
        'is_popular': True,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'ingredients_ar': 'طبقة علوية غير منسوجة، لُب ماص فائق الامتصاص من البوليمر، طبقة خلفية قابلة للتهوية',
        'image_file': '144.png',
    },
    {
        'name': 'Peri Classic Soft Normal Sanitary Pads, 10 pcs',
        'name_ar': 'فوط بيري الصحية الكلاسيكية الناعمة العادية (10 قطع)',
        'slug': 'peri-classic-soft-normal-sanitary-pads-10-pcs',
        'description': 'Normal-absorbency sanitary pads with a soft cotton-like top surface and 5 layers of protection, 10-count pack.',
        'description_ar': 'فوط صحية بامتصاص عادي وسطح علوي ناعم يشبه القطن مع 5 طبقات حماية، عبوة من 10 قطع.',
        'price': 13.5,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'sku': 'FEM-043',
        'stock': 110,
        'rating': 4.3,
        'is_featured': True,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'ingredients_ar': 'طبقة علوية غير منسوجة، لُب ماص فائق الامتصاص من البوليمر، طبقة خلفية قابلة للتهوية',
        'image_file': '254.png',
    },
    {
        'name': 'Peri Classic Night Sanitary Pads, 10 pcs',
        'name_ar': 'فوط بيري الصحية الكلاسيكية الليلية (10 قطع)',
        'slug': 'peri-classic-night-sanitary-pads-10-pcs',
        'description': 'Night-use sanitary pads with a mesh top surface and 5 layers of protection for overnight coverage, 10-count pack.',
        'description_ar': 'فوط صحية للاستخدام الليلي بسطح علوي شبكي و5 طبقات حماية لتغطية ليلية كاملة، عبوة من 10 قطع.',
        'price': 13.5,
        'old_price': 16,
        'category_slug': 'feminine-hygiene',
        'brand_slug': 'peri',
        'badge': '-16%',
        'badge_ar': '-16%',
        'sku': 'FEM-042',
        'stock': 100,
        'rating': 4.2,
        'ingredients': 'Non-woven top sheet, super-absorbent polymer core, breathable back sheet',
        'ingredients_ar': 'طبقة علوية غير منسوجة، لُب ماص فائق الامتصاص من البوليمر، طبقة خلفية قابلة للتهوية',
        'image_file': '253.png',
    },

    # ─── Specialty Wipes ────────────────────────────────────────
    {
        'name': 'Sunlight Make-Up Remover Wipes (20 pcs)',
        'name_ar': 'مناديل صن لايت المبللة لإزالة المكياج (20 منديلاً)',
        'slug': 'sunlight-make-up-remover-wipes-20-pcs',
        'description': 'Wet wipes formulated for makeup removal, packaged in a pink-and-gold floral pack of 20.',
        'description_ar': 'مناديل مبللة مخصصة لإزالة المكياج، معبأة في عبوة زهرية بألوان وردية وذهبية، 20 منديلاً.',
        'price': 3.0,
        'category_slug': 'specialty-wipes',
        'brand_slug': 'sunlight',
        'sku': 'SPW-001',
        'stock': 60,
        'rating': 4.3,
        'ingredients': 'Purified water, glycerin, mild surfactant, plant extract, fragrance',
        'ingredients_ar': 'ماء نقي، جليسرين، مادة خافضة للتوتر السطحي لطيفة، مستخلص نباتي، عطر',
        'image_file': '29.png',
    },
    {
        'name': 'Sunlight Intimate Hygiene Wipes (20 pcs)',
        'name_ar': 'مناديل صن لايت المبللة للنظافة الحميمة (20 منديلاً)',
        'slug': 'sunlight-intimate-hygiene-wipes-20-pcs',
        'description': 'Wet wipes formulated for intimate hygiene, packaged in a soft pink-and-blue floral pack of 20.',
        'description_ar': 'مناديل مبللة مخصصة للنظافة الحميمة، معبأة في عبوة زهرية ناعمة بألوان وردية وزرقاء، 20 منديلاً.',
        'price': 3.0,
        'category_slug': 'specialty-wipes',
        'brand_slug': 'sunlight',
        'sku': 'SPW-002',
        'stock': 70,
        'rating': 4.4,
        'ingredients': 'Purified water, glycerin, mild surfactant, plant extract, fragrance',
        'ingredients_ar': 'ماء نقي، جليسرين، مادة خافضة للتوتر السطحي لطيفة، مستخلص نباتي، عطر',
        'image_file': '30.png',
    },

    # ─── Household Cleaning ─────────────────────────────────────
    {
        'name': 'Sunlight For Home Wet Wipes XL (70 pcs)',
        'name_ar': 'مناديل صن لايت المنزلية الكبيرة (70 منديلاً)',
        'slug': 'sunlight-for-home-wet-wipes-xl-70-pcs',
        'description': 'XL household cleaning wipes with a unique foaming formula that leave floors, mirrors, and other surfaces streak-free, 70 count.',
        'description_ar': 'مناديل تنظيف منزلية بحجم كبير بتركيبة رغوية فريدة تترك الأرضيات والمرايا والأسطح الأخرى نظيفة دون خطوط، 70 منديلاً.',
        'price': 13.9,
        'category_slug': 'household-cleaning',
        'brand_slug': 'sunlight',
        'sku': 'HCL-002',
        'stock': 130,
        'rating': 4.9,
        'ingredients': 'Non-woven viscose-blend fabric, mild surfactant',
        'ingredients_ar': 'قماش غير منسوج من مزيج الفيسكوز، مادة خافضة للتوتر السطحي لطيفة',
        'image_file': '24.png',
    },
    {
        'name': 'Sunlight Universal Flat Mop',
        'name_ar': 'ممسحة صن لايت المسطحة الشاملة',
        'slug': 'sunlight-universal-flat-mop',
        'description': 'A collapsible, universal flat mop by Sunlight designed for wet floor cleaning; this is a reusable cleaning tool, not a disposable wipe or tissue.',
        'description_ar': 'ممسحة مسطحة قابلة للطي من صن لايت مصممة لتنظيف الأرضيات الرطبة؛ هذه أداة تنظيف قابلة لإعادة الاستخدام، وليست منديلاً مبللاً يُستخدم لمرة واحدة.',
        'price': 16.0,
        'category_slug': 'household-cleaning',
        'brand_slug': 'sunlight',
        'badge': 'New',
        'badge_ar': 'جديد',
        'sku': 'HCL-012',
        'stock': 80,
        'rating': 4.3,
        'ingredients': 'Non-woven viscose-blend fabric, mild surfactant',
        'ingredients_ar': 'قماش غير منسوج من مزيج الفيسكوز، مادة خافضة للتوتر السطحي لطيفة',
        'image_file': '288.png',
    },

    # ─── HoReCa Disposables ─────────────────────────────────────
    {
        'name': 'Sunlight Disposable Non-Woven Bed Sheet Roll, White (80x190cm)',
        'name_ar': 'لفة ملاءات صن لايت غير المنسوجة القابلة للتصرف - أبيض (80×190 سم)',
        'slug': 'sunlight-disposable-bed-sheet-roll-white',
        'description': 'A single roll of white disposable non-woven bed sheeting, 80x190cm per sheet, for hotels, spas, clinics, and salons.',
        'description_ar': 'لفة واحدة من ملاءات السرير البيضاء غير المنسوجة القابلة للتصرف، بمقاس 80×190 سم للملاءة الواحدة، مخصصة للفنادق والمنتجعات الصحية والعيادات وصالونات التجميل.',
        'price': 38,
        'category_slug': 'horeca-disposables',
        'brand_slug': 'sunlight',
        'sku': 'HCR-001',
        'stock': 40,
        'rating': 4.3,
        'ingredients': 'Non-woven spunbond fabric',
        'ingredients_ar': 'قماش سبونبوند غير منسوج',
        'image_file': '337.jpg',
    },
]
