# Generated by Django 6.0.8 on 2026-09-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'support message', 'verbose_name_plural': 'support messages'},
        ),
    ]
