# Generated by Django 6.0.8 on 2026-08-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Sunlight Group', max_length=255),
        ),
    ]
