# Generated by Django 6.0.8 on 2026-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_activitylog_options_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='GoldenSunlight', max_length=255),
        ),
    ]
