# Generated by Django 6.0.8 on 2026-09-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_sitesettings_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10),
        ),
    ]
