# Generated by Django 6.0.8 on 2026-09-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_sitesettings_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
