# Generated by Django 6.0.8 on 2026-08-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_pending_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pending_role',
            field=models.CharField(blank=True, choices=[('staff', 'Customer'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='', help_text="Django admin orqali berilgan, lekin foydalanuvchi profilini (ism, familiya, telefon, rasm) to'ldirmaguncha kuchga kirmaydigan rol.", max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Customer'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='staff', max_length=20),
        ),
    ]
