# Generated by Django 6.0.8 on 2026-09-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_pending_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pending_role',
            field=models.CharField(blank=True, choices=[('staff', 'Customer'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='', help_text='Role granted via Django admin, but not yet in effect until the user completes their profile (first name, last name, phone, avatar).', max_length=20),
        ),
    ]
